spring.application.name=attendancesystem

# Render dynamic port
server.port=${PORT:8080}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/attendanceDB}

# Hardcoded Admin Credentials
admin.username=admin
admin.password=admin123

# JWT Secret Key
jwt.secret=734767jkhgkjhg65876587FGHJGHG87g87gJHGFjhgjhg68765876gjhgJHGF

# Company Location Details
company.location.latitude=12.292223
company.location.longitude=78.507496
company.location.radius.meters=500
